permalink: /:year-:month-:day-:title.html
paginate: 5
url: http://localhost:4000
exclude: [README.md, _themes]
timezone: Europe/Berlin
markdown: redcarpet
redcarpet:
  extensions: ["no_intra_emphasis", "fenced_code_blocks", "autolink", "strikethrough", "superscript", "underline", "highlight"]

title: Jekyll Boilerstrap
author: Sebastian Teumert
theme: jekyll-boilerstrap
