permalink: /:year-:month-:day-:title.html
paginate: 5
url: http://localhost
exclude: [README.md]
timezone: Europe/Berlin
markdown: redcarpet
redcarpet:
  extensions: ["no_intra_emphasis", "fenced_code_blocks", "autolink", "strikethrough", "superscript", "underline", "highlight"]

